# Generated by Django 3.0.6 on 2020-05-20 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='org/', verbose_name='机构封面')),
                ('name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('course_num', models.IntegerField(default=0, verbose_name='课程数')),
                ('study_num', models.IntegerField(default=0, verbose_name='学习人数')),
                ('address', models.CharField(max_length=20, verbose_name='机构地址')),
                ('desc', models.CharField(max_length=200, verbose_name='机构简介')),
                ('detail', models.TextField(verbose_name='机构详情')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_num', models.IntegerField(default=0, verbose_name='访问量')),
                ('category', models.IntegerField(choices=[(0, '培训机构'), (1, '高校'), (2, '个人')], verbose_name='机构类别')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('cityinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.CityInfo', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机构信息',
                'verbose_name_plural': '机构信息',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='teacher/', verbose_name='教师头像')),
                ('name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('auth', models.IntegerField(choices=[(0, '普通讲师'), (1, '高级讲师'), (2, '金牌讲师')], default=0, verbose_name='认证类型')),
                ('work_year', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_position', models.IntegerField(verbose_name='工作职位')),
                ('age', models.IntegerField(verbose_name='教师年龄')),
                ('work_style', models.CharField(max_length=200, verbose_name='教学特点')),
                ('gender', models.CharField(choices=[('boy', '男'), ('girl', '女')], default='boy', max_length=10, verbose_name='教师性别')),
                ('love_num', models.IntegerField(default=0, verbose_name='收藏量')),
                ('click_num', models.IntegerField(default=0, verbose_name='访问量')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('work_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.OrgInfo', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
            },
        ),
    ]
